apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  # ClusterIP — Ingress routes /* traffic here
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
